<package format="2">
  <name>rqt_graph_focus</name>
  <version>1.0.0</version>
  <description>rqt_graph_focus is a fork of rqt_graph with click-to-focus
      and connection list features. Click on a node or topic to filter
      the graph to show only connected elements.
  </description>
  <maintainer email="michael.jeronimo@openrobotics.org">Michael Jeronimo</maintainer>
  <maintainer email="william@openrobotics.org">William Woodall</maintainer>
  <license>BSD</license>
  <url type="website">http://wiki.ros.org/rqt_graph</url>
  <url type="repository">https://github.com/ros-visualization/rqt_graph</url>
  <url type="bugtracker">https://github.com/ros-visualization/rqt_graph/issues</url>
  <author email="dthomas@osrfoundation.org">Dirk Thomas</author>
  <author email="ablasdel@gmail.com">Aaron Blasdel</author>

  <exec_depend>ament_index_python</exec_depend>
  <exec_depend>python_qt_binding</exec_depend>
  <exec_depend version_gte="1.1.2">qt_dotgraph</exec_depend>
  <exec_depend>rqt_gui</exec_depend>
  <exec_depend>rqt_gui_py</exec_depend>

  <export>
    <build_type>ament_python</build_type>
    <rqt_gui plugin="${prefix}/plugin.xml"/>
  </export>
</package>
